title: "Development Experiences"
author: "Tristan Possessky"
description: "Just wanted to write about some of the code I write becuase its fun." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "tristanlpossessky@gmail.com"
github_username: "tpossessky"
linkedin_username: "https://www.linkedin.com/in/tristan-possessky-01160616a/"

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
